### ISSUE TITLE
Slow reload time of SpeckleProperties

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-unity#104]
Right now, `SpeckleProperties` component serializes a lot of data, using our custom serializer which was optimised for serializing lots of objects in bulk, not small single objects.

We should scope some alternatives that provide equivalent DX, but are more optimal for serialization and memory performance.

**Comment by JR-Morgan** [comment]
see https://github.com/specklesystems/speckle-sharp/pull/2967

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
