### ISSUE TITLE
Missing Stream Prefab 

### ISSUE THREAD

**Issue by haitheredavid** [specklesystems/speckle-unity#14]
Example scene requires stream prefab that has some buttons and text fields setup but that prefab seems to be missing from the project. It might be helpful to have an example scene that doesn't rely on any ui assets. I've started extracting some of the example code into a general stream manager component ([mos def a wip](https://github.com/haitheredavid/speckle-unity/blob/dm/playspace/Assets/Speckle%20Connector/dmo/BabyStreamManager.cs)).

**Comment by teocomi** [comment]
Hey David, I'm actually updating that scene now a bit and adding a new tutorial. 
Will make sure not to forget it this time :)

P.S.
The prefab is used just to instantiate some UI elements, but there's maybe a better way to do so!

**Comment by haitheredavid** [comment]
hihi- that sounds great, thanks for the info! The stream manager takes a lot of reference from your example obj, with the main difference being a [custom editor](https://github.com/haitheredavid/speckle-unity/blob/dm/playspace/Assets/Speckle%20Connector/dmo/Editor/BabyStreamManagerEditor.cs) to make the speckle setup side a bit more cleaner. I'd be happy to share once I shape it up a bit more :D

**Comment by teocomi** [comment]
Amazing, I'm a total Unity noob, so it'd be great to get schooled on how to do things properly :)
Maybe catch up sometime this week?

**Comment by haitheredavid** [comment]
fur sure! to the calendar 🚀
