### ISSUE TITLE
Generate material assets on recieve in editor mode

### ISSUE THREAD

**Issue by pkratten** [specklesystems/speckle-unity#30]
Hi!

I think it is very useful to generate the materials that are used in an received model to easily adjust the look and to ease the usage of the receiver for beginners.

I created a solution for review here:
https://github.com/pkratten/speckle-unity/commit/52133c15fc2d9eeb69cfb396256aa247b233f932

Have a nice day!
Peter

**Comment by teocomi** [comment]
Looks good! Thanks Peter, I'll give it a spin in the next week.
Feel free to make a PR in the meantime...
