### ISSUE TITLE
Use of UnityEditor breaks builds

### ISSUE THREAD

**Issue by psarras** [specklesystems/speckle-unity#37]
I tried to make a build but it is not allowed to use UnityEditor namespace on builds. I commented out the effected lines and managed to build. If you can clarify what this code is meant to do I am sure we can find a workaround. No file is using this directly.

Infected file: ```RosolynDirectoryCreator.cs```

![image](https://user-images.githubusercontent.com/3820417/129169107-60969c0d-873f-4147-b0cb-d9e8eceb7a44.png)

**Comment by teocomi** [comment]
Hey, I was using that `RosolynDirectoryCreator` because of some weird Unity errors that were randomly showing in the editor, so feel free to remove it if you don't need it!
