### ISSUE TITLE
Allowing for different Kits and Converters

### ISSUE THREAD

**Issue by haitheredavid** [specklesystems/speckle-unity#56]
Putting an issue on the board that builds off of #54. Currently there is no ability to switch out the converter for custom objects as the receiving code is hardcoded in the package. This creates a blockers for our dependency on speckle in unity.

**Comment by JR-Morgan** [comment]
Closing for now.
The current `RecursiveConverter` component does allow users to specify their own converter, although not exposed in the UI, users can quite easily specify their own converter through code.

We are aware of further DX improvements we can make in our converters, and we aim to slowly work towards easier customisation of conversion functions.
