### ISSUE TITLE
Improvements for Android platforms

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-unity#68]
Discussion started over on [this thread ](https://speckle.community/t/unity-android-build/3104).

Currently, The Unity connector builds fine for all platforms (except IL2CPP dependent ones)
However, There are some significant limitations for non-desktop platforms.

- [ ] SQLite cache does not work out of the box, and it being the default local transport, causes problems.
- [ ] No mechanism to load accounts.

It is, however, possible to manually receive through a hardcoded auth token, and manually specifying an alternative local transport (E.g. memory transport).

See https://github.com/specklesystems/speckle-unity/blob/main/Assets/Extra/ManualReceive.cs

Additionally, there are a number of ways we can improve the DX for Android/IOS builds.
 - [ ] Add Android/IOS to our release testing cycle.
 - [ ] Scope web based auth improvements.
 - [ ] Scope transport improvements.
 - [ ] Scope full SQLite support.

See discussion 
- https://speckle.community/t/unity-android-build/3104
- https://speckle.community/t/receiving-speckle-streams-in-ios-apps/1910
 - #22

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
