### ISSUE TITLE
Publish on unity package manager

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-unity#7]
Current installation through git has some disadvantages
 - Users not notified of updates
 - Versioning is difficult (requires knowledge of unity's git syntax)
 - Requires git
 
UPM solves these issues, as well as allowing us to bundle sample projects in a convenient manor.

**Comment by haitheredavid** [comment]
@teocomi I could help with getting this setup with OpenUPM. It might require some reviewing on project structure before we go down that route, but it's not a heavy lift... I've done this process for other unity projects

**Comment by teocomi** [comment]
Thanks David! Feel free to investigate what changes would be needed from our end, fyi we're not planning to focus on Unity work for the next sprint so we'll be able to pick this up around September!

**Comment by haitheredavid** [comment]
sounds good! god speed with the sprint 🗡️

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
