### ISSUE TITLE
Slow loading times on Operations.Receive

### ISSUE THREAD

**Issue by LukasKlepper** [specklesystems/speckle-unity#76]
Hi,

we are currently having issues with long loading times within unity with the latest connector.
When we are getting an object with ~10k objects then we need to wait ~4min (at least!) for just the Receiving operation of speckle.
The algorithm which generates the game objects from the base object only takes around ~30seconds which is really good for that amount of objects.

The problem is at file Receiver.cs @ line 134.

`        var @base = await Operations.Receive(
          objectId,
          remoteTransport: transport,
          onErrorAction: OnErrorAction,
          onProgressAction: OnProgressAction,
          onTotalChildrenCountKnown: OnTotalChildrenCountKnown,
          disposeTransports: true
        );`

Nearly the same code which I reproduced on .NET Core 3.1 Console Application with the latest NuGet package of speckle core only needs ~45seconds.

Why is it so slow? Is it a known problem? What can I do to speed it up?
We are using the connector within an application for an 3d cave environment with a customer.
Later on we want to load even larger models, the customer already told us that he experienced loading times up to **40 minutes**.

The test above were taken both from our cave application and the provided unity speckle playground. There was no difference in performance.

I also tried to upgrade the speckle connectors speckle sharp dlls manually to the latest version, which also didn't help. Same issue.

Tested on hardware:
11th Gen Intel Core i7 1165G7 @ 2,8GHz
16GB DDR4 RAM 3200MHz
SSD
Integrated Graphics

**Comment by JR-Morgan** [comment]
After some further testing, I am noticing some quite significant slowness even in Unity 2021.

Compared with a .NET project, the Deserialisation appears to be around 10x slower in Unity 😢 not good.
Going to do some more rigorous measurements, and continue investigating.

**Comment by LukasKlepper** [comment]
I've tested it with unity 2019, 2020 and 2021 each with mono and il2cpp scripting background. There was no measureable performance difference.

What's strange: Shouldn't the models be cached? Then the second loading time should be much faster than the first, but it is not.

Unfortunately, I can not share the model, as it is a model from the customer.

**Comment by haitheredavid** [comment]
hi, I might be able to help clarify what's happening here. I don't think the issue with `Operations.Receive` but with the conversion routines from a speckle stream to native unity geometry. 

> The algorithm which generates the game objects from the base object only takes around ~30seconds which is really good for that amount of objects.

This part ends up happening **after** the receive command has completed and starts dropping all the speckle data into the [conversion process](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/Receiver.cs#L146), and then I'm assuming that's where the long 20-40 minute delays are coming in. It doesn't matter if the geometry is cached locally on your machine, the conversion process still needs to rebuild all the speckle goodness into the unity scene. The converters are currently all bound to run on the main unity thread, and also have a few steps for serializing a speckle object that are creating the bottleneck. 

I have some PR's coming in the near future that will address these issues. In the meantime, @LukasKlepper how are you using the connector? Is it for visualization purposes? If you don't need to worry about the properties of your objects and you're comfortable with jumping around the code you could comment out the part in the converter that uses [`SpeckleProperties`](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/ConverterUnity.Geometry.cs#L277-L287), that would reduce the conversion overhead a bit.

**Comment by LukasKlepper** [comment]
Hi @haitheredavid ,

thanks for you answer. So correct me if im wrong:

the line [Receiver.cs@134](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/Receiver.cs#L134) takes part of getting all the data from the speckle server. Thats just the base informations which later on will be converted to game objects which get feeded with the speckle properties. We also use that exactly same method in other applications which build up on speckle, but in asp.net core server applications rather than unity. In other projects this method is very fast (~30 seconds for the same model as in unity)

the line [Receiver.cs@142-152](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/Receiver.cs#L142) takes those informations from the base object and then converts this base information to unity game objects ands adds the speckle properties to it. It gets queded by the Dispatcher to the main thread as only there you can build game objects or access specific api calls. Of course thats slower than multi-theading but I think thats the way unity currently works on the classical API. I'm not a unity expert so thats a pure idea: Maybe Unity DOTS is a way how those game objects could be built up multi threaded? I've never done it so I dont know if that could solve the problem of conversion process, but as you will later on read, thats (for me) not as much of a problem.

I've debugged the code with visual studio and got to the point where I moved trough it via procedure steps (so for every new call I needed to press it manually). For the timing I grabbed my phone and stopped the watch for the time I've started the method and when it arrived at the next call.

Thats the way I calculated (debugged) that the lines:

134: [`var @base = await Operations.Receive(...)`](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/Receiver.cs#L134) takes around ~4min

146: [`var go = rc.ConvertRecursivelyToNative(@base, commitId);`](https://github.com/specklesystems/speckle-unity/blob/8aaec04705365acaa9e9e94a1ee94e66d3bd7523/Packages/systems.speckle.speckle-unity/Receiver.cs#L146) takes around ~30 seconds (sometimes its longer, but no longer than one minute)

for a model with ~10k objects in both Unity 2020 and Unity 2021.

Is that a wrong way to calculate it? Did I make an mistake? Or is Operations.Receive already doing a conversion in the background?

---

To answer your question: We are currently visualising a model to walk through it like in a vr application but in a [cave](https://en.wikipedia.org/wiki/Cave_automatic_virtual_environment). Later on there will be also the need to select objects and look at the speckle properties, so removing those properties is not a solution.

**Comment by LukasKlepper** [comment]
@haitheredavid Hi there,

i've just retested it, the operation now took 250 seconds with stopwatch for just the receiving part of speckle. I dont know why its so slow. Also interestingly I cannot even load the model in speckle.xyz. Its just loading forever. The model comes out of revit, its ~10k mep objects.

Code used to benchmark:

133: `var transport = new ServerTransport(Client.Account, StreamId);`
134: `System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();`
135: `Debug.Log("Starting stopwatch Operations.Receive().");`
136: `sw.Start();`
137: `var @base = await Operations.Receive(
          objectId,
          remoteTransport: transport,
          onErrorAction: OnErrorAction,
          onProgressAction: OnProgressAction,
          onTotalChildrenCountKnown: OnTotalChildrenCountKnown,
          disposeTransports: true
        );`
145: `sw.Stop();`
146: `Debug.Log($"Stopped stopwatch Operations.Receive(). Stopwatch took {sw.Elapsed.TotalSeconds} seconds.");`

The properties are there, after the stopwatch finished it just took seconds before the model was shown in unity. I dont think its a problem with the unity converter rather than the communication in the DLL between Unity and Speckle. Maybe its because its mono underneath and not native .net?

![grafik](https://user-images.githubusercontent.com/69464569/191035039-34180047-1e0d-4070-ac6e-6047e5cfff8f.png)

As you see the models are relatively detailed and its the basic properties of mep objects, nothing fancy.

As of the performance things we already knew that, thats why our customer machine is very beefy:

- gpu 2x RTX 3090
- cpu 5950x
- 32 gb ram
- ssd

Im sure it should be able to handle even more objects than ~10k as they are all static, but correct me if im wrong.

Im looking forward to the DOTS support, I always wanted to try it :)

**Comment by LukasKlepper** [comment]
Hi, are there any news up on this issue? Our problem still exisits within unity.

**Comment by JR-Morgan** [comment]
> Hi, are there any news up on this issue? Our problem still exisits within unity.

Hi @LukasKlepper, 
If you have time, please could you try the latest version of the Unity Connector.
I've made several improvements to the editor time receiving process that should have some noticeable speed-ups on receive performance.

---

For now, just the editor `Speckle Receiver` component has these improvements.

In a future update, I would like to consolidate these components with the runtime receiving components used in the Playground sample project.

---

When you get the chance, I'd greatly appreciate any feedback.
If you still think we need to improve performance, I can re-open this issue in our sharp SDK repo.
