### ISSUE TITLE
Consolidate Editor and Runtime components

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-unity#85]
Currently, the editor only `StreamManager` component duplicates a lot of behaviour of the `Receiver` component designed for runtime usage.

Ideally, I'd like to see one component that can be used for both runtime and editor in the same way.
- [x] Allows both sending and receiving
- [x] Generic account/stream/branch/commit selection
- [x] Exposed events (similar to blender's Receive/Send scripts)
- [ ] Auto-receive / subscriptions
- [ ] Extensibility for more complex runtime behaviour (filters, scene management, etc)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
