### ISSUE TITLE
Speckle comments on wrong position/location

### ISSUE THREAD

**Issue by LukasKlepper** [specklesystems/speckle-unity#89]
Hi there,

we are currently trying to integrate the speckle comments on a stream within unity.
For that we firstly wanted to just show the comments as basic game objects w/o any text or context.

I've had no problems getting the comments, but as I've looked at the location something wasn't correct. The comments from the graph ql api seem to return the (wrong?) locations.

Where I've expected it to be:
![grafik](https://user-images.githubusercontent.com/69464569/219028149-5f5bd25f-e1d8-4d27-8e7a-a1915c9d78c0.png)

Where it actually is: (the green dot represents it)
![grafik](https://user-images.githubusercontent.com/69464569/219028292-4eb1b807-d4cb-41e7-98f8-3172505a29ac.png)

I've used the [data.location](https://github.com/specklesystems/speckle-sharp/blob/7d13f65ab64400d2c3d535c1592a49719f7eba9d/Core/Core/Api/GraphQL/Models.cs#L413) property from a [CommentItem](https://github.com/specklesystems/speckle-sharp/blob/7d13f65ab64400d2c3d535c1592a49719f7eba9d/Core/Core/Api/GraphQL/Models.cs#L418)

Im sure that the coordinates are correct as I've checked against the graphql api explorer from speckle.xyz.
![grafik](https://user-images.githubusercontent.com/69464569/219029507-cf34c308-af85-4bf5-9152-8101e1456216.png)
![grafik](https://user-images.githubusercontent.com/69464569/219029601-30941630-c55b-4f9b-839f-9b9a038d0a57.png)

Code:

```
    public void LoadComments(string streamId, string streamName, GameObject go)
    {
        var comments = speckleLoader.Client.StreamGetComments(streamId).Result;
        foreach (var item in comments.items)
        {
            var comment = GameObject.Instantiate(commentPrefab, new Vector3((float)item.data.location.x, (float)item.data.location.y, (float)item.data.location.z), Quaternion.identity, go.transform);
            comment.name = $"Comment #{item.id}";
        }
    }
```

For our use case we would need the exact position like in the speckle viewer seen in the first picture.

I don't know if it fits in this correct repository as ait also seems to connect to Speckle.Core, please dont kill me!

**Comment by LukasKlepper** [comment]
Any news on this? @teocomi @JR-Morgan

**Comment by JR-Morgan** [comment]
Hi @LukasKlepper, Sorry for the delayed response,

This looks really exciting. 🙌

My suspicion is that the coordinate system that unity uses is slightly different from what we use in our comments (and objects) 
We have this function in the Unity Converter to correct for this. 
 https://github.com/specklesystems/speckle-unity/blob/db2b8312780d7b79784f2c6dc6c0962c0b040f0f/Packages/systems.speckle.speckle-unity/Runtime/Converter/Unity/ConverterUnity.Geometry.cs#L33

**Comment by JR-Morgan** [comment]
@LukasKlepper 
Were you able to resolve your issue?

I'm closing this issue for now, If you still need assistance, you can re-open this issue or reach out to us on [speckle.community](https://speckle.community/)
